# Generated by Django 4.0.2 on 2022-02-12 04:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import workspaces.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workspaces', '0003_tag_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to=workspaces.models.upload_to),
        ),
        migrations.AddField(
            model_name='file',
            name='richText',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='adviser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adviser+', to=settings.AUTH_USER_MODEL),
        ),
    ]
