# Generated by Django 4.0.2 on 2022-02-14 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0004_file_pdf_file_richtext_alter_workspace_adviser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workspace',
            name='isShared',
        ),
    ]
