# Generated by Django 4.0.2 on 2022-02-14 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0005_remove_workspace_isshared'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='tags',
        ),
        migrations.AddField(
            model_name='file',
            name='status',
            field=models.CharField(choices=[('ongoing', 'Ongoing'), ('done', 'Done'), ('submitted', 'Submitted'), ('published', 'Published'), ('archive', 'Archived')], default='ongoing', max_length=12),
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
