# Generated by Django 4.0.2 on 2022-02-14 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0006_remove_file_tags_file_status_delete_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
    ]
