# Generated by Django 4.0.2 on 2022-02-16 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0002_alter_verification_document'),
        ('classrooms', '0002_alter_comment_options_alter_recommendation_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='institution',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='institutions.institution'),
            preserve_default=False,
        ),
    ]
