# Generated by Django 4.0.2 on 2022-02-18 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_profilecover_account_profileimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='type',
            field=models.CharField(blank=True, choices=[('moderator', 'Moderator'), ('adviser', 'Adviser'), ('researcher', 'Researcher')], max_length=16, null=True),
        ),
    ]
