# Generated by Django 3.2 on 2022-02-28 20:58

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_account_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='profileCover',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.upload_to, verbose_name='ProfileCover'),
        ),
        migrations.AlterField(
            model_name='account',
            name='profileImage',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.upload_to, verbose_name='ProfileImage'),
        ),
    ]
