# Generated by Django 4.0.2 on 2022-02-26 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_conversation_isactive_message_isactive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
