# Generated by Django 3.2 on 2022-03-01 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_alter_conversation_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='name',
            field=models.CharField(blank=True, default='no name', max_length=255, null=True),
        ),
    ]
