# Generated by Django 4.0.2 on 2022-02-22 01:40

from django.db import migrations, models
import publication.models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to=publication.models.upload_to),
        ),
    ]
