# Generated by Django 4.0.2 on 2022-02-21 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0002_alter_verification_document'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='instance',
            new_name='institution',
        ),
    ]
