# Generated by Django 4.0.2 on 2022-02-21 06:52

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('institutions', '0003_rename_instance_member_institution'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='member',
            unique_together={('user', 'institution')},
        ),
    ]
