# Generated by Django 4.0.2 on 2022-02-16 01:59

from django.db import migrations, models
import django.db.models.deletion
import resources.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institutions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('isExclusive', models.BooleanField(default=False)),
                ('isActive', models.BooleanField(default=True)),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
                ('dateUpdated', models.DateTimeField(auto_now=True)),
                ('imports', models.IntegerField(default=0)),
                ('richText', models.TextField(blank=True, null=True)),
                ('pdf', models.FileField(blank=True, null=True, upload_to=resources.models.upload_to)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.institution')),
            ],
            options={
                'ordering': ('-dateUpdated',),
            },
        ),
    ]
