# Generated by Django 4.0.2 on 2022-02-16 07:40

from django.db import migrations, models
import resources.models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='pdf',
            field=models.FileField(blank=True, default=None, null=True, upload_to=resources.models.upload_to, verbose_name='resourcePDF'),
        ),
    ]
