# Generated by Django 4.0.2 on 2022-02-16 07:52

from django.db import migrations, models
import resources.models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_alter_resource_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='pdf',
            field=models.FileField(null=True, upload_to=resources.models.upload_to),
        ),
    ]
